### PR TITLE
Added support for LSTM layers as well as Embedding layers.

### PR DESCRIPTION
**Pull request by javierfvargas**
Added support for LSTM layers as well as Embedding layers.

Also included a couple of activations: sigmoid, hard-sigmoid and tanh.
Some additional code to operate tensors included.
Full python export and test generators included for given layers and activations.

I also set some methods of KerasModel to virtual in order to ease Mocking during testing in my projects.

### CODE REVIEW

**Comment by moof2k** [comment]
Thanks for the PR! I refactored your modifications to Tensor a little, hope you don't mind..

**Comment by javierfvargas** [comment]
Thanks for accepting it, your lib was really useful for me. And about modifications to tensor, I don't mind, you are in charge of keeping the style.  ;)

**Comment by moof2k** [comment]
hey @javierfvargas I noticed if you compile with -DDEBUG the LSTM unit tests fail, it looks like KerasLayerLSTM::Apply produces a 2 dimensional tensor whereas the unit test is expecting a 1D tensor.

**Comment by javierfvargas** [comment]
Let me check it on Monday.

**Comment by javierfvargas** [comment]
@moof2k I have it fixed now.  It was a mistake on how the tensor is build when the LSTM doesn't  have to return sequences.  But I also found similar problem on the embedding layer.   Fixed an tests passing with -DDEBUG

What should we do now? Another pull request?

**Comment by moof2k** [comment]
yes please :)

**Pull request merged**
